language: node_js

node_js:
  - "7"
  - "8"
  - "9"
  - "10"

before_script:
  - npm run build
  - npm run bootstrap

after_success:
  - npm run coveralls

cache:
  directories:
    - node_modules

git:
  depth: 5
