import * as echarts from 'echarts/core'

import {
  BarChart,
  LineChart,
  LinesChart,
  EffectScatterChart,
  PieChart,
  HeatmapChart,
  GraphChart,
  FunnelChart,
  SunburstChart,
  ThemeRiverChart,
  CustomChart,
  ParallelChart,
  SankeyChart,
  GaugeChart,
  MapChart,
  PictorialBarChart,
  RadarChart,
  ScatterChart
} from 'echarts/charts'

import {
  TitleComponent,
  TooltipComponent,
  BrushComponent,
  GridComponent,
  PolarComponent,
  MarkLineComponent,
  SingleAxisComponent,
  AriaComponent,
  ParallelComponent,
  LegendComponent,
  RadarComponent,
  ToolboxComponent,
  DataZoomComponent,
  VisualMapComponent,
  TimelineComponent,
  CalendarComponent,
  GraphicComponent
} from 'echarts/components'

echarts.use([
  LegendComponent,
  TitleComponent,
  TooltipComponent,
  GridComponent,
  PolarComponent,
  AriaComponent,
  ParallelComponent,
  ThemeRiverChart,
  BarChart,
  LineChart,
  LinesChart,
  EffectScatterChart,
  HeatmapChart,
  GraphChart,
  FunnelChart,
  CustomChart,
  GaugeChart,
  SunburstChart,
  ParallelChart,
  SankeyChart,
  PieChart,
  MapChart,
  RadarChart,
  PictorialBarChart,
  RadarComponent,
  ToolboxComponent,
  BrushComponent,
  DataZoomComponent,
  VisualMapComponent,
  TimelineComponent,
  MarkLineComponent,
  SingleAxisComponent,
  CalendarComponent,
  GraphicComponent,
  ScatterChart
])

export default echarts
