export default {
  models: {
    'stock.warehouse': {
      fields: [
        'name',
        'active',
        'company_id',
        'partner_id',
        'view_location_id',
        'lot_stock_id',
        'code',
        'route_ids',
        'reception_steps',
        'delivery_steps',
        'wh_input_stock_loc_id',
        'wh_qc_stock_loc_id',
        'wh_output_stock_loc_id',
        'wh_pack_stock_loc_id',
        'mto_pull_id',
        'pick_type_id',
        'pack_type_id',
        'out_type_id',
        'in_type_id',
        'int_type_id',
        'crossdock_route_id',
        'reception_route_id',
        'delivery_route_id',
        'warehouse_count',
        'resupply_wh_ids',
        'resupply_route_ids',
        'show_resupply',
      ],
    },

    'stock.warehouse.orderpoint': {
      fields: [
        'name',
        'active',
        'warehouse_id',
        'location_id',
        'product_id',
        'product_uom',
        'product_min_qty',
        'product_max_qty',
        'qty_multiple',
        'group_id',
        'company_id',
        'lead_days',
        'lead_type',
      ],
    },
  },
};
