export default {
  models: {
    'stock.move.line': {
      fields: [
        'picking_id',
        'move_id',
        'product_id',
        'product_uom_id',
        'product_qty',
        'product_uom_qty',
        'qty_done',
        'package_id',
        'package_level_id',
        'lot_id',
        'lot_name',
        'result_package_id',
        'date',
        'owner_id',
        'location_id',
        'location_dest_id',
        'lots_visible',
        'picking_type_use_create_lots',
        'picking_type_use_existing_lots',
        'state',
        'is_initial_demand_editable',
        'is_locked',
        'consume_line_ids',
        'produce_line_ids',
        'reference',
        'tracking',
        'picking_type_entire_packs',
      ],
    },
  },
};
