export default {
  models: {
    'stock.picking.type': {
      fields: [
        'name',
        'color',
        'sequence',
        'sequence_id',
        'default_location_src_id',
        'default_location_dest_id',
        'code',
        'return_picking_type_id',
        'warehouse_id',
        'active',
        'use_create_lots',
        'use_existing_lots',
        'show_operations',
        'show_reserved',
        'last_done_picking',
        'count_picking_draft',
        'count_picking_ready',
        'count_picking',
        'count_picking_waiting',
        'count_picking_late',
        'count_picking_backorders',
        'rate_picking_late',
        'rate_picking_backorders',
        'barcode',
      ],
    },

    'stock.picking': {
      fields: [
        'name',
        'origin',
        'note',
        'backorder_id',
        'backorder_ids',
        'move_type',
        'state',
        'group_id',
        'priority',
        'scheduled_date',
        'date',
        'date_done',
        'location_id',
        'location_dest_id',
        'move_lines',
        'move_ids_without_package',
        'has_scrap_move',
        'picking_type_id',
        'picking_type_code',
        'picking_type_entire_packs',
        'partner_id',
        'company_id',
        'move_line_ids',
        'move_line_ids_without_package',
        'move_line_exist',
        'has_packages',
        'show_check_availability',
        'show_mark_as_todo',
        'show_validate',
        'owner_id',
        'printed',
        'is_locked',
        'product_id',
        'show_operations',
        'show_lots_text',
        'has_tracking',
        'immediate_transfer',
        'package_level_ids',
        'package_level_ids_details',
      ],
    },
  },
};
